-- Create design_extraction_jobs table
CREATE TABLE design_extraction_jobs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR2(255) NOT NULL UNIQUE,
    status VARCHAR2(50) NOT NULL,
    design_url VARCHAR2(500),
    design_id VARCHAR2(255),
    confidence NUMBER(5,2),
    error_message CLOB,
    options CLOB,
    created_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    mockup_url VARCHAR2(500),
    callback_url VARCHAR2(500),
    worker_secret VARCHAR2(255)
);

-- Create indexes for better performance
CREATE INDEX idx_design_extraction_jobs_job_id ON design_extraction_jobs(job_id);
CREATE INDEX idx_design_extraction_jobs_status ON design_extraction_jobs(status);
CREATE INDEX idx_design_extraction_jobs_created_at ON design_extraction_jobs(created_at);
CREATE INDEX idx_design_extraction_jobs_processed_at ON design_extraction_jobs(processed_at);

-- Add comments
COMMENT ON TABLE design_extraction_jobs IS 'Table for storing design extraction job information';
COMMENT ON COLUMN design_extraction_jobs.job_id IS 'Unique job identifier';
COMMENT ON COLUMN design_extraction_jobs.status IS 'Job status: PROCESSING, COMPLETED, FAILED';
COMMENT ON COLUMN design_extraction_jobs.design_url IS 'URL of extracted design image';
COMMENT ON COLUMN design_extraction_jobs.design_id IS 'Unique design identifier';
COMMENT ON COLUMN design_extraction_jobs.confidence IS 'Confidence score (0-100)';
COMMENT ON COLUMN design_extraction_jobs.error_message IS 'Error message if job failed';
COMMENT ON COLUMN design_extraction_jobs.options IS 'JSON string of extraction options';
COMMENT ON COLUMN design_extraction_jobs.created_at IS 'Job creation timestamp';
COMMENT ON COLUMN design_extraction_jobs.processed_at IS 'Job completion timestamp';
COMMENT ON COLUMN design_extraction_jobs.mockup_url IS 'URL of original mockup image';
COMMENT ON COLUMN design_extraction_jobs.callback_url IS 'Callback URL for job completion';
COMMENT ON COLUMN design_extraction_jobs.worker_secret IS 'Worker secret for authentication';

